// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/demo.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UserInfo struct {
	//primary key
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//age
	Age int32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	//address
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfo) Reset()         { *m = GetInfo{} }
func (m *GetInfo) String() string { return proto.CompactTextString(m) }
func (*GetInfo) ProtoMessage()    {}
func (*GetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{2}
}

func (m *GetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo.Unmarshal(m, b)
}
func (m *GetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo.Marshal(b, m, deterministic)
}
func (m *GetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo.Merge(m, src)
}
func (m *GetInfo) XXX_Size() int {
	return xxx_messageInfo_GetInfo.Size(m)
}
func (m *GetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo proto.InternalMessageInfo

type GetInfo_Request struct {
	//primary key
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//page num
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	//limit
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfo_Request) Reset()         { *m = GetInfo_Request{} }
func (m *GetInfo_Request) String() string { return proto.CompactTextString(m) }
func (*GetInfo_Request) ProtoMessage()    {}
func (*GetInfo_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{2, 0}
}

func (m *GetInfo_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo_Request.Unmarshal(m, b)
}
func (m *GetInfo_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo_Request.Marshal(b, m, deterministic)
}
func (m *GetInfo_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo_Request.Merge(m, src)
}
func (m *GetInfo_Request) XXX_Size() int {
	return xxx_messageInfo_GetInfo_Request.Size(m)
}
func (m *GetInfo_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo_Request proto.InternalMessageInfo

func (m *GetInfo_Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetInfo_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfo_Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetInfo_Request) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetInfo_Response struct {
	//list data
	List                 []*UserInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetInfo_Response) Reset()         { *m = GetInfo_Response{} }
func (m *GetInfo_Response) String() string { return proto.CompactTextString(m) }
func (*GetInfo_Response) ProtoMessage()    {}
func (*GetInfo_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{2, 1}
}

func (m *GetInfo_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo_Response.Unmarshal(m, b)
}
func (m *GetInfo_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo_Response.Marshal(b, m, deterministic)
}
func (m *GetInfo_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo_Response.Merge(m, src)
}
func (m *GetInfo_Response) XXX_Size() int {
	return xxx_messageInfo_GetInfo_Response.Size(m)
}
func (m *GetInfo_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo_Response proto.InternalMessageInfo

func (m *GetInfo_Response) GetList() []*UserInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type CreateInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInfo) Reset()         { *m = CreateInfo{} }
func (m *CreateInfo) String() string { return proto.CompactTextString(m) }
func (*CreateInfo) ProtoMessage()    {}
func (*CreateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{3}
}

func (m *CreateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInfo.Unmarshal(m, b)
}
func (m *CreateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInfo.Marshal(b, m, deterministic)
}
func (m *CreateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInfo.Merge(m, src)
}
func (m *CreateInfo) XXX_Size() int {
	return xxx_messageInfo_CreateInfo.Size(m)
}
func (m *CreateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInfo proto.InternalMessageInfo

type CreateInfo_Request struct {
	//name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//page num
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	//limit
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInfo_Request) Reset()         { *m = CreateInfo_Request{} }
func (m *CreateInfo_Request) String() string { return proto.CompactTextString(m) }
func (*CreateInfo_Request) ProtoMessage()    {}
func (*CreateInfo_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{3, 0}
}

func (m *CreateInfo_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInfo_Request.Unmarshal(m, b)
}
func (m *CreateInfo_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInfo_Request.Marshal(b, m, deterministic)
}
func (m *CreateInfo_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInfo_Request.Merge(m, src)
}
func (m *CreateInfo_Request) XXX_Size() int {
	return xxx_messageInfo_CreateInfo_Request.Size(m)
}
func (m *CreateInfo_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInfo_Request proto.InternalMessageInfo

func (m *CreateInfo_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateInfo_Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CreateInfo_Request) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UpdateInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfo) Reset()         { *m = UpdateInfo{} }
func (m *UpdateInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateInfo) ProtoMessage()    {}
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{4}
}

func (m *UpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfo.Unmarshal(m, b)
}
func (m *UpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfo.Marshal(b, m, deterministic)
}
func (m *UpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfo.Merge(m, src)
}
func (m *UpdateInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateInfo.Size(m)
}
func (m *UpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfo proto.InternalMessageInfo

type UpdateInfo_Request struct {
	//primary key
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//page num
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	//limit
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfo_Request) Reset()         { *m = UpdateInfo_Request{} }
func (m *UpdateInfo_Request) String() string { return proto.CompactTextString(m) }
func (*UpdateInfo_Request) ProtoMessage()    {}
func (*UpdateInfo_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{4, 0}
}

func (m *UpdateInfo_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfo_Request.Unmarshal(m, b)
}
func (m *UpdateInfo_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfo_Request.Marshal(b, m, deterministic)
}
func (m *UpdateInfo_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfo_Request.Merge(m, src)
}
func (m *UpdateInfo_Request) XXX_Size() int {
	return xxx_messageInfo_UpdateInfo_Request.Size(m)
}
func (m *UpdateInfo_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfo_Request proto.InternalMessageInfo

func (m *UpdateInfo_Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateInfo_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateInfo_Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UpdateInfo_Request) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DeleteInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInfo) Reset()         { *m = DeleteInfo{} }
func (m *DeleteInfo) String() string { return proto.CompactTextString(m) }
func (*DeleteInfo) ProtoMessage()    {}
func (*DeleteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{5}
}

func (m *DeleteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInfo.Unmarshal(m, b)
}
func (m *DeleteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInfo.Marshal(b, m, deterministic)
}
func (m *DeleteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInfo.Merge(m, src)
}
func (m *DeleteInfo) XXX_Size() int {
	return xxx_messageInfo_DeleteInfo.Size(m)
}
func (m *DeleteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInfo proto.InternalMessageInfo

type DeleteInfo_Request struct {
	//primary key
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInfo_Request) Reset()         { *m = DeleteInfo_Request{} }
func (m *DeleteInfo_Request) String() string { return proto.CompactTextString(m) }
func (*DeleteInfo_Request) ProtoMessage()    {}
func (*DeleteInfo_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{5, 0}
}

func (m *DeleteInfo_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInfo_Request.Unmarshal(m, b)
}
func (m *DeleteInfo_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInfo_Request.Marshal(b, m, deterministic)
}
func (m *DeleteInfo_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInfo_Request.Merge(m, src)
}
func (m *DeleteInfo_Request) XXX_Size() int {
	return xxx_messageInfo_DeleteInfo_Request.Size(m)
}
func (m *DeleteInfo_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInfo_Request proto.InternalMessageInfo

func (m *DeleteInfo_Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "api.Response")
	proto.RegisterType((*UserInfo)(nil), "api.UserInfo")
	proto.RegisterType((*GetInfo)(nil), "api.GetInfo")
	proto.RegisterType((*GetInfo_Request)(nil), "api.GetInfo.Request")
	proto.RegisterType((*GetInfo_Response)(nil), "api.GetInfo.Response")
	proto.RegisterType((*CreateInfo)(nil), "api.CreateInfo")
	proto.RegisterType((*CreateInfo_Request)(nil), "api.CreateInfo.Request")
	proto.RegisterType((*UpdateInfo)(nil), "api.UpdateInfo")
	proto.RegisterType((*UpdateInfo_Request)(nil), "api.UpdateInfo.Request")
	proto.RegisterType((*DeleteInfo)(nil), "api.DeleteInfo")
	proto.RegisterType((*DeleteInfo_Request)(nil), "api.DeleteInfo.Request")
}

func init() { proto.RegisterFile("api/demo.proto", fileDescriptor_982f2043e503afee) }

var fileDescriptor_982f2043e503afee = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xdd, 0xaa, 0xd3, 0x40,
	0x10, 0xc7, 0xc9, 0x97, 0x39, 0x67, 0xf4, 0x1c, 0x74, 0x39, 0xd2, 0x18, 0xbc, 0xa8, 0x7b, 0x63,
	0x29, 0x98, 0x48, 0xbd, 0xeb, 0xa5, 0x1f, 0x14, 0x2f, 0xbc, 0x59, 0x28, 0x42, 0xef, 0xd6, 0xee,
	0x18, 0x16, 0x92, 0x6c, 0xcc, 0x6e, 0x5f, 0xc0, 0x37, 0x10, 0xdf, 0xc6, 0xd7, 0xf0, 0x15, 0x7c,
	0x10, 0xd9, 0x49, 0xda, 0x14, 0x41, 0x28, 0x88, 0x77, 0xb3, 0xb3, 0xf3, 0xff, 0xcd, 0xcc, 0x7f,
	0x59, 0xb8, 0x95, 0x9d, 0x2e, 0x15, 0x36, 0xa6, 0xe8, 0x7a, 0xe3, 0x0c, 0x8b, 0x64, 0xa7, 0xf3,
	0xa7, 0x95, 0x31, 0x55, 0x8d, 0xa5, 0xbf, 0x93, 0x6d, 0x6b, 0x9c, 0x74, 0xda, 0xb4, 0x76, 0x28,
	0xe1, 0x2f, 0xe1, 0x4a, 0xa0, 0xed, 0x4c, 0x6b, 0x91, 0x3d, 0x84, 0xa8, 0xb1, 0x55, 0x16, 0xcc,
	0x83, 0xc5, 0xb5, 0xf0, 0x21, 0x63, 0x10, 0xef, 0x8d, 0xc2, 0x2c, 0x9c, 0x07, 0x8b, 0x44, 0x50,
	0xcc, 0x77, 0x70, 0xb5, 0xb5, 0xd8, 0xbf, 0x6f, 0x3f, 0x1b, 0x76, 0x0b, 0xa1, 0x56, 0x24, 0x88,
	0x44, 0xa8, 0x95, 0xaf, 0x6f, 0x65, 0x33, 0xd4, 0x5f, 0x0b, 0x8a, 0x3d, 0x55, 0x56, 0x98, 0x45,
	0x84, 0xf0, 0x21, 0xcb, 0x20, 0x95, 0x4a, 0xf5, 0x68, 0x6d, 0x16, 0x53, 0xe1, 0xf1, 0xc8, 0xbf,
	0x05, 0x90, 0x6e, 0xd0, 0x79, 0x76, 0xfe, 0x11, 0x52, 0x81, 0x5f, 0x0e, 0x68, 0xdd, 0x45, 0x6d,
	0x18, 0xc4, 0xdd, 0xd4, 0x87, 0x62, 0x76, 0x07, 0x49, 0xad, 0x1b, 0xed, 0xa8, 0x4d, 0x22, 0x86,
	0x43, 0xfe, 0xe2, 0x6c, 0xe5, 0x67, 0x10, 0xd7, 0xda, 0xba, 0x2c, 0x98, 0x47, 0x8b, 0xfb, 0xab,
	0x9b, 0x42, 0x76, 0xba, 0x38, 0x6e, 0x27, 0xe8, 0x8a, 0x6f, 0x01, 0xde, 0xf4, 0x28, 0x1d, 0xd2,
	0x54, 0x9b, 0x69, 0xaa, 0x7f, 0x9a, 0x82, 0x23, 0xc0, 0xb6, 0x53, 0x47, 0xec, 0xff, 0x5a, 0x96,
	0x3f, 0x07, 0x78, 0x8b, 0x35, 0x8e, 0x6d, 0x9e, 0xfc, 0xb5, 0xcd, 0xea, 0x47, 0x08, 0x31, 0xbd,
	0xe9, 0xbb, 0xd3, 0x13, 0xb0, 0x3b, 0xf2, 0x63, 0x3c, 0x15, 0xa3, 0x32, 0x7f, 0xfc, 0x47, 0x76,
	0xb0, 0x92, 0xdf, 0x7c, 0xfd, 0xf9, 0xeb, 0x7b, 0x98, 0xb2, 0xa4, 0xd4, 0x5e, 0xfb, 0xe1, 0xdc,
	0x36, 0x36, 0x23, 0xcd, 0x94, 0x38, 0xc1, 0x06, 0xcb, 0x4f, 0x90, 0x19, 0x41, 0x1e, 0xf1, 0x07,
	0x04, 0x29, 0xf7, 0x24, 0x58, 0x07, 0x4b, 0x8f, 0x9b, 0xec, 0x1a, 0x71, 0x53, 0xe2, 0x42, 0xdc,
	0x81, 0x04, 0x23, 0x6e, 0xb2, 0x65, 0xc4, 0x4d, 0x89, 0x0b, 0x71, 0x8a, 0x04, 0xeb, 0x60, 0xf9,
	0x3a, 0xd9, 0xf9, 0xaf, 0xf6, 0xe9, 0x1e, 0xfd, 0xa9, 0x57, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x0a, 0x1f, 0x4c, 0x6f, 0x88, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InfoClient is the client API for Info service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfoClient interface {
	GetInfo(ctx context.Context, in *GetInfo_Request, opts ...grpc.CallOption) (*GetInfo_Response, error)
	CreateInfo(ctx context.Context, in *CreateInfo_Request, opts ...grpc.CallOption) (*Response, error)
	UpdateInfo(ctx context.Context, in *UpdateInfo_Request, opts ...grpc.CallOption) (*Response, error)
	DeleteInfo(ctx context.Context, in *DeleteInfo_Request, opts ...grpc.CallOption) (*Response, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) GetInfo(ctx context.Context, in *GetInfo_Request, opts ...grpc.CallOption) (*GetInfo_Response, error) {
	out := new(GetInfo_Response)
	err := c.cc.Invoke(ctx, "/api.Info/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoClient) CreateInfo(ctx context.Context, in *CreateInfo_Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Info/CreateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoClient) UpdateInfo(ctx context.Context, in *UpdateInfo_Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Info/UpdateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoClient) DeleteInfo(ctx context.Context, in *DeleteInfo_Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Info/DeleteInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServer is the server API for Info service.
type InfoServer interface {
	GetInfo(context.Context, *GetInfo_Request) (*GetInfo_Response, error)
	CreateInfo(context.Context, *CreateInfo_Request) (*Response, error)
	UpdateInfo(context.Context, *UpdateInfo_Request) (*Response, error)
	DeleteInfo(context.Context, *DeleteInfo_Request) (*Response, error)
}

// UnimplementedInfoServer can be embedded to have forward compatible implementations.
type UnimplementedInfoServer struct {
}

func (*UnimplementedInfoServer) GetInfo(ctx context.Context, req *GetInfo_Request) (*GetInfo_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedInfoServer) CreateInfo(ctx context.Context, req *CreateInfo_Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInfo not implemented")
}
func (*UnimplementedInfoServer) UpdateInfo(ctx context.Context, req *UpdateInfo_Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInfo not implemented")
}
func (*UnimplementedInfoServer) DeleteInfo(ctx context.Context, req *DeleteInfo_Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInfo not implemented")
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Info/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).GetInfo(ctx, req.(*GetInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Info_CreateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).CreateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Info/CreateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).CreateInfo(ctx, req.(*CreateInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Info_UpdateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).UpdateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Info/UpdateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).UpdateInfo(ctx, req.(*UpdateInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Info_DeleteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).DeleteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Info/DeleteInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).DeleteInfo(ctx, req.(*DeleteInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Info_GetInfo_Handler,
		},
		{
			MethodName: "CreateInfo",
			Handler:    _Info_CreateInfo_Handler,
		},
		{
			MethodName: "UpdateInfo",
			Handler:    _Info_UpdateInfo_Handler,
		},
		{
			MethodName: "DeleteInfo",
			Handler:    _Info_DeleteInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/demo.proto",
}
